### ISSUE TITLE
breaking down the reverse-eng, for http requests

### ISSUE THREAD

**Issue by JangoBritt** [vanstinator/raincloudy#40]
Hey @tchellomello, this is really great work with the reverse engineering.

I've never developed with Python, or groovy, or Java, so I'm totally out of luck for trying to use your library.

I see that you're using http for the communication to the controller. I'm wondering if there's any way to break it down even further so that the valves could be opened and closed with a simple HTTP request?

I'm thinking that could be a way to use that with homebridge to create a water controller device type or, at the very least, a switch.

**Comment by tchellomello** [comment]
Hello @JangoBritt, 
Thanks for your kind words. I was only the one that started the work, but lately, @vanstinator  has been helping a lot to the project. 
In a nutshell, to open or close a valve is due to an HTTP request, however, due to the implementation on Melnor's side, there are some rules and processes you have to do in order to acquire a token and be authorized to do it. 

You could create a script that uses `raincloudy` on the backend and make it compatible with HomeBridge. I don't have nor used HomeBridge, but if you can plug a custom script there, you can use the library to help you out with this integration. 

If you want o to create a connector or extend the library to Homebridge, it would be very appreciated too. 

Thanks!

**Comment by vanstinator** [comment]
Will have to agree with @tchellomello here. The best course of action would probably be building a wrapper around `raincloudy` to make this work. _Personally_ I'd rather see this approach than adding Homebridge functionality to this repo. I'd prefer to see `raincloudy` stay simple and implementation agnostic.
